### PR TITLE
Update translation_cz.xml

### PR DESCRIPTION
**Pull request by kikislany**

### CODE REVIEW

**Comment by stijnwop** [comment]
Please don't change the %sm value.. that one is used to format the size of the hose into the text and will throw errors on the game if you remove it.

So that results into `3m` or `5m` depending on the hose..
Which makes the entire entry: `Místo pro uložení 5m je malé!`

**Comment by kikislany** [comment]
Ok, sorry for that, but i test it today and every time i get only 3m warnings and not 5m so i think and is better for my language to use universal word  hadice -> hose.  Its probably not yet implemented or i make something wrong. On the screenshot i have 5m hose.

fsScreen_2020_03_24_16_12_14

**Comment by stijnwop** [comment]
Euhm sorry my bad. It replaces it with the size of the parking place.. not the hose length xD

That annaburger only allows for 3M hoses to be parked, those 5m are too big.

**Comment by stijnwop** [comment]
But looks good now. 👍

**Comment by kikislany** [comment]
Ah, so its my bad i understand it wrong :(  I corrected it so its right now.

**Comment by stijnwop** [comment]
@kikislany Cool! 

I did a little tweak to the `global_configuration_disappearOnEmpty` translation for the english version and changed it to `Standard`. Not sure if that still fits with your translation?

**Comment by kikislany** [comment]
I think its ok, in Czech we are more desriptive as in other languages

**Pull request merged**
